name: trust
description: A logistics app called Trust

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  firebase_core: ^3.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  
  cloud_firestore: ^5.1.0
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.1
  flutter_colorpicker: ^1.0.3
  fluttertoast: ^8.2.6
  smooth_page_indicator: ^1.2.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.8
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.0
  permission_handler: ^11.3.1
  
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/user.svg
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/R.jpg
    - assets/images/Klano.jpg
